receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319
      http:
        endpoint: 0.0.0.0:4320
extensions:
  jaeger_query:
    storage:
      traces: memstore
  jaeger_storage:
    backends:
      memstore:
        memory:
          max_traces: 10000
exporters:
  jaeger_storage_exporter:
    trace_storage: memstore
service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger_storage_exporter]
